### ISSUE TITLE
Closing issues using keywords does not work anymore

### ISSUE THREAD

**Issue by rvanlaak** [phstc/probot-merge-when-green#5] opened 2019-03-26 10:49 UTC
Issues do not get closed anymore when closing keywords are put in the PR description, and when the bot then does the merge.

## References

https://help.github.com/en/articles/closing-issues-using-keywords

:pushpin: <s>#10</s>

:pushpin: <s>#11</s>

:pushpin: #12

**Comment by phstc** [comment] 2019-04-13 10:12
hi @rvanlaak 

The closing keywords still seem to be working for me. In your case, when the bot merges a pull requests it isn't closing the respective issues (closing keywords)?

**Comment by phstc** [comment] 2019-04-27 16:14
hi @rvanlaak 

just checking it again?

**Comment by rvanlaak** [comment] 2019-04-29 07:55
It seems to happen every now and then, but we can not make a solid reproduction scenario.  

So, let's close this for now. Thanks for following up!

**Comment by rvanlaak** [comment] 2019-05-02 09:41
Going to reopen this one, as it just happened again. We manually had to close the issue after merge bot did merge the PR.

**Comment by phstc** [comment] 2019-05-02 15:01
@rvanlaak is the issue public? If so, can you link me it? If it is not, can you send me a screenshot of the pull request (target + description)? 

If a pull request is merged, closing the fixable issues is not something with Merge when green. GitHub is the one that does the auto closing. 

Make sure that the pull request with the "Fixes" is targeting the default branch (by default `master`). 

![image](https://user-images.githubusercontent.com/105652/57084952-3da59980-6cc9-11e9-9a2d-3cda8a31a494.png)

Closing keywords don't work for pull requests targeting a non-default branch.

Also, "Fixes 123, 456" - does not work, it needs to be "Fixes 123 Fixes 456 ...".

**Comment by rvanlaak** [comment] 2019-05-17 08:18
I'm sorry, these repos are not public. Did send you an email with the info. Usually it's quite easy to come up with a reproduction scenario, but this time we are not sure about what is happening. As you also said, it's probably Github that does the closing based on the keyword. Let's hope we can get this resolved, let me know if you need additional help.

**Comment by phstc** [comment] 2019-05-17 13:04
Thank you @rvanlaak. I've just replied your e-mail. Please, let me know how it goes.

**Comment by webmaster128** [comment] 2019-06-13 17:18
We have this issue consistently with the Closing description text "Closes #928". See
- https://github.com/iov-one/iov-core/pull/1086 for the latest event
- https://github.com/iov-one/iov-core/pulls?q=is%3Apr+is%3Aclosed+label%3A%22merge+when+green%22 for a bunch of examples

**Comment by phstc** [comment] 2019-06-13 17:32
@webmaster128 thank you! I've just sent an email to GitHub support. I hope they can help with that. Otherwise, I could try to add a "closing keyword" feature to this bot. I added a similar feature to another bot (I wanted to trigger a closing keyword for non-master merges).

**Comment by webmaster128** [comment] 2019-06-13 18:18
Glad to hear. I guess the preferred way is to rely on Github's native keyword interpretation to avoid any kind of behaviour differences.

I did a quick look how merges are performed, but there seems to be nothing configurable in https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button, which is probably used by probot. So I'd expect the "Merge button" API works the same way as the merge button does.

Looking forward to hear from the support.

**Comment by phstc** [comment] 2019-06-13 19:51
I'm 100% with on relying on GitHub's native implementation 🙏 

I could reproduce the problem in #8 with #9.

> I did a quick look how merges are performed, but there seems to be nothing configurable in https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button, which is probably used by probot. So I'd expect the "Merge button" API works the same way as the merge button does.

Thanks for researching that.  I agree, I believe it should behave the same.

> Looking forward to hear from the support.

🤞

**Closed** 2019-06-16 21:23 UTC

**Comment by phstc** [comment] 2019-06-16 21:54
hey hey

The mystery has been solved 🎉 

After playing back-and-forth, even trying some non-sense stuff. I found the problem!

![](https://media.giphy.com/media/c7PcKQlOqZ8Ws/giphy.gif)

The bot needs issue write permissions, otherwise [closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords) will fail silently (╯°□°)╯︵ ┻━┻ 

You both should have received a notification asking for MOAR permissions. Once you accepted the request, auto closing should work 👇 

![image](https://user-images.githubusercontent.com/105652/59570010-63131a80-905f-11e9-90a1-cd831471c991.png)
